- name: Remove apt lock file
  file:
    state: absent
    path: "/var/lib/dpkg/lock-frontend"
  become: true
  tags: apt

- name: Install all required dependencies
  apt:
    name: ['python', 'python-setuptools', 'python-dev', 'build-essential', 'python3-pip', 'python3-mysqldb']
    state: latest
  become: yes
  become_user: root